---

version: 1

disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s | %(levelname)s | %(module)s | %(message)s"
    verbose:
        format: "%(asctime)s | %(levelname)s | %(module)s | %(processName)s:%(threadName)s | %(filename)s:%(lineno)s | %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    logfile:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        when: midnight
        filename: twiti.log
        backupCount: 30

    error_log:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: verbose
        filename: error.log
        maxBytes: 10485760
        backupCount: 5

root:
    level: DEBUG
    handlers: [logfile, error_log]
